SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

TILE_SIZE = 48
PANEL_WIDTH = 300
ZOOM_MIN = 0.3
ZOOM_MAX = 2.0
ZOOM_STEP = 0.1
CAMERA_SCROLL_SPEED = 12
EDGE_SCROLL_SPEED = 8

MAP_OFFSET_X = 0
MAP_OFFSET_Y = 0

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GRAY = (100, 100, 100)
LIGHT_GRAY = (180, 180, 180)
DARK_GRAY = (60, 60, 60)
RED = (220, 50, 50)
GREEN = (50, 200, 50)
BLUE = (50, 100, 220)
YELLOW = (220, 220, 50)
ORANGE = (220, 140, 20)
BROWN = (140, 90, 30)
DARK_GREEN = (30, 80, 30)
CYAN = (50, 200, 200)
PURPLE = (160, 50, 200)
BEIGE = (210, 190, 140)
DARK_BLUE = (20, 40, 100)

# Terrain types
FIELD = 0
FOREST = 1
CITY = 2
ROAD = 3
RIVER = 4

TERRAIN_COLORS = {
    FIELD: (100, 160, 60),
    FOREST: (30, 90, 30),
    CITY: (160, 140, 120),
    ROAD: (140, 130, 110),
    RIVER: (50, 100, 200),
}

TERRAIN_NAMES = {
    FIELD: "Поле",
    FOREST: "Лес",
    CITY: "Город",
    ROAD: "Дорога",
    RIVER: "Река",
}

TERRAIN_MOVEMENT_COST = {
    FIELD: 1,
    FOREST: 2,
    CITY: 1,
    ROAD: 0.5,
    RIVER: 99,
}

TERRAIN_DEFENSE_BONUS = {
    FIELD: 0,
    FOREST: 20,
    CITY: 40,
    ROAD: 0,
    RIVER: 0,
}

TERRAIN_COVER_BONUS = {
    FIELD: 0,
    FOREST: 25,
    CITY: 50,
    ROAD: 0,
    RIVER: 0,
}

# HoMM-style movement points per turn
# Пехота = 1 шаг за ход (любая местность)
# Техника = больше очков, зависит от местности
INFANTRY_MOVE_POINTS = 10   # Хватит на любую клетку, но лимит 1 шаг
TANK_MOVE_POINTS = 4
TRUCK_MOVE_POINTS = 4
ARTILLERY_MOVE_POINTS = 3
DRONE_MOVE_POINTS = 6
SOLDIER_UNIT_MOVE_POINTS = 10  # 1 шаг за ход
RADAR_EW_MOVE_POINTS = 3

# Максимальное количество шагов за ход
INFANTRY_STEPS_PER_TURN = 1
TANK_STEPS_PER_TURN = 3
TRUCK_STEPS_PER_TURN = 3
ARTILLERY_STEPS_PER_TURN = 2
DRONE_STEPS_PER_TURN = 5
SOLDIER_STEPS_PER_TURN = 1
RADAR_EW_STEPS_PER_TURN = 2

# Vision
VISION_RANGE = {
    "infantry": 2,
    "tank": 3,
    "drone": 5,
    "artillery": 2,
    "soldier_unit": 2,
    "radar_ew": 3,
}

# Unit types
INFANTRY = "infantry"
TANK = "tank"
RECON_DRONE = "recon_drone"
FPV_DRONE = "fpv_drone"
FPV_OPERATOR = "fpv_operator"
SUPPLY_TRUCK = "supply_truck"
WAREHOUSE = "warehouse"
RECON_OPERATOR = "recon_operator"
ARTILLERY = "artillery"
SOLDIER_UNIT = "soldier_unit"
RADAR_EW = "radar_ew"

# Unit parameters
INFANTRY_INIT_SOLDIERS = 8
INFANTRY_MAX_SOLDIERS = 999
INFANTRY_BASE_FOOD_PER_TURN = 1
INFANTRY_MAX_AMMO = 30
INFANTRY_MAX_FOOD = 100
INFANTRY_MAX_ENTRENCH = 100
INFANTRY_ATTACK_RANGE = 1
INFANTRY_BASE_HIT_CHANCE = 60
INFANTRY_MORALE_MAX = 100
SOLDIER_FOOD_WEIGHT = 0.3
SOLDIER_WEIGHT = 10
SOLDIER_MAX_FOOD = 40
SOLDIER_MAX_AMMO = 5
SOLDIER_FOOD_PER_TURN = 1
SOLDIER_FOOD_INTERVAL = 1
SOLDIER_TURNS_WITHOUT_FOOD_DEATH = 3
SOLDIER_CARRY_CAPACITY = 40

TANK_INIT_CREW = 3
TANK_MIN_CREW = 3
TANK_MAX_CREW = 999
TANK_MAX_ARMOR = 100
TANK_MAX_AMMO = 15
TANK_MAX_FUEL = 30
TANK_ATTACK_RANGE = 2
TANK_BASE_HIT_CHANCE = 90
TANK_CARRY_CAPACITY = 20
TANK_CARRY_FOOD = 0
TANK_CARRY_AMMO = 0

ARTILLERY_INIT_CREW = 4
ARTILLERY_MAX_CREW = 999
ARTILLERY_MAX_AMMO = 8
ARTILLERY_MAX_ENTRENCH = 100
ARTILLERY_ATTACK_RANGE = 5
ARTILLERY_BARRAGE_RANGE = 30
ARTILLERY_DAMAGE = 4

RADAR_EW = "radar_ew"
RADAR_EW_INIT_CREW = 4
RADAR_EW_MIN_CREW = 2
RADAR_EW_MAX_CREW = 999
RADAR_EW_MAX_FOOD = 100
RADAR_EW_MAX_AMMO = 20
RADAR_EW_JAM_RANGE = 5
RADAR_EW_MAX_FUEL = 60
RADAR_EW_FUEL_PER_TURN = 3

MAP_WIDTH = 75
MAP_HEIGHT = 54

DRONE_MAX_BATTERY = 96
DRONE_VISION_RANGE = 6
DRONE_LOW_BATTERY_THRESHOLD = 20

FPV_OPERATOR_INIT_CREW = 2
FPV_OPERATOR_MIN_CREW = 2
FPV_OPERATOR_MAX_STOCK = 5
FPV_OPERATOR_MAX_FOOD = 100
FPV_OPERATOR_MAX_AMMO = 30
FPV_OPERATOR_RANGE = 30
FPV_AUTO_TARGET = True
FPV_MOVE_SPEED = 5
FPV_MAX_PER_TURN = 1

FPV_HIT_CHANCE_BASE = 0.80
FPV_HIT_EW_PENALTY = 0.20
FPV_HIT_FOREST_PENALTY = 0.20
FPV_HIT_CITY_PENALTY = 0.10
FPV_INFANTRY_SHOOTDOWN_CHANCE = 0.15
FPV_NO_LOS_PENALTY = 0.25

TRUCK_CARGO_CAPACITY = 20
TRUCK_MAX_WEIGHT = 300
TRUCK_MAX_FUEL = 15
TRUCK_INIT_CREW = 1
TRUCK_MIN_CREW = 1
TRUCK_MAX_CREW = 999
RECON_OPERATOR_INIT_CREW = 1
RECON_OPERATOR_MIN_CREW = 1
RECON_OPERATOR_MAX_CREW = 999
RECON_OPERATOR_MAX_FOOD = 100
RECON_OPERATOR_MAX_AMMO = 20

WAREHOUSE_CAPACITY = 100

# Radar
RADAR_RANGE = 25
RADAR_WAVE_SPEED = 0.5
RADAR_OPERATOR_RANGE = 25

# Supply consumption
FOOD_CONSUMPTION_INTERVAL = 1
FUEL_CONSUMPTION = 1

# Combat
FPV_HIT_CHANCE_BASE = 0.8
FPV_DAMAGE_INFANTRY = 5
FPV_DAMAGE_ARMOR = 30

# Turns
MAX_TURNS = 40
SUPPLY_REINFORCEMENT_INTERVAL = 25

# Unit reinforcement intervals (in turns)
REINFORCEMENT_INFANTRY_INTERVAL = 25
REINFORCEMENT_TANK_INTERVAL = 25
REINFORCEMENT_DRONE_INTERVAL = 25
REINFORCEMENT_FPV_INTERVAL = 25

# Cargo types
CARGO_SUPPLIES = "supplies"
CARGO_AMMO = "ammo"
CARGO_FUEL = "fuel"
CARGO_BATTERIES = "batteries"
CARGO_FPV_DRONE = "fpv_drone"
CARGO_RECON_DRONE = "recon_drone"
CARGO_NAMES = {
    CARGO_SUPPLIES: "Припасы",
    CARGO_AMMO: "Боезапас",
    CARGO_FUEL: "Топливо",
    CARGO_BATTERIES: "Батареи",
    CARGO_FPV_DRONE: "FPV-дроны",
    CARGO_RECON_DRONE: "Разведдроны",
}

CARGO_WEIGHT_PER_UNIT = {
    CARGO_SUPPLIES: 5,
    CARGO_AMMO: 10,
    CARGO_FUEL: 8,
    CARGO_BATTERIES: 3,
    CARGO_FPV_DRONE: 15,
    CARGO_RECON_DRONE: 20,
}

# Factions
PLAYER = 0
ENEMY = 1

# Game phases
PHASE_PLANNING = 0
PHASE_MOVEMENT = 1
PHASE_DETECTION = 2
PHASE_RANGED_COMBAT = 3
PHASE_CLOSE_COMBAT = 4
PHASE_LOGISTICS = 5
PHASE_ENTRENCH = 6
PHASE_ENEMY_TURN = 7

PHASE_NAMES = {
    PHASE_PLANNING: "Планирование",
    PHASE_MOVEMENT: "Движение",
    PHASE_DETECTION: "Обнаружение",
    PHASE_RANGED_COMBAT: "Дальний бой",
    PHASE_CLOSE_COMBAT: "Ближний бой",
    PHASE_LOGISTICS: "Логистика",
    PHASE_ENTRENCH: "Укрепления",
    PHASE_ENEMY_TURN: "Ход противника",
}

# Directions
DIRECTIONS = [(0, -1), (0, 1), (-1, 0), (1, 0)]

# =============================================================================
# SOLDIER PARAMETERS
# =============================================================================
SOLDIER_MAX_HEALTH = 100
SOLDIER_SKILL_COUNT_MIN = 2
SOLDIER_SKILL_COUNT_MAX = 4
SOLDIER_INIT_EXPERIENCE_MIN = 0
SOLDIER_INIT_EXPERIENCE_MAX = 20
SOLDIER_INIT_MORALE_MIN = 50
SOLDIER_INIT_MORALE_MAX = 100
SOLDIER_MAX_EXPERIENCE = 100
SOLDIER_SKILL_BONUS_PER_SKILL = 5

# Wound thresholds
WOUND_THRESHOLD_NONE = 75
WOUND_THRESHOLD_LIGHT = 50
WOUND_THRESHOLD_MEDIUM = 25

# Heal targets
HEALTH_AFTER_HEAL_NONE = 80
HEALTH_AFTER_HEAL_LIGHT = 55
HEALTH_AFTER_HEAL_MEDIUM = 30

# Medic
MEDIC_BASE_TREAT_CHANCE = 30
MEDIC_SKILL_TREAT_BONUS = 10

# =============================================================================
# INFANTRY COMBAT PARAMETERS
# =============================================================================
INFANTRY_NORMAL_SQUAD_SIZE = 8
INFANTRY_ATTACK_POWER_DIVISOR = 2
INFANTRY_OVERLOAD_ATTACK_PENALTY = 0.5
INFANTRY_LOW_MORALE_THRESHOLD = 30
INFANTRY_LOW_MORALE_HIT_PENALTY = -20
INFANTRY_OVERCROWD_HIT_PENALTY = 2
INFANTRY_OVERLOAD_HIT_PENALTY_FACTOR = 30
INFANTRY_HUNGRY_HIT_PENALTY = 15
INFANTRY_WOUND_HIT_PENALTY_FACTOR = 30
INFANTRY_MIN_HIT_CHANCE = 10

# Camouflage
INFANTRY_BASE_CAMOUFLAGE = 40
INFANTRY_OVERCROWD_CAMOUFLAGE_PENALTY = 5
ENTRENCH_CAMOUFLAGE_THRESHOLD = 50
ENTRENCH_CAMOUFLAGE_BONUS = 10
INFANTRY_OVERLOAD_CAMOUFLAGE_PENALTY_FACTOR = 20

# Entrenchment
ENTRENCH_STEP_AMOUNT = 20
ENTRENCH_ABSORPTION_DIVISOR = 200
ENTRENCH_DAMAGE_REDUCTION_DIVISOR = 20

# Morale
INFANTRY_OVERCROWD_MORALE_PENALTY = 1

# =============================================================================
# TANK COMBAT PARAMETERS
# =============================================================================
TANK_INIT_CARRY_FOOD = 100
TANK_MAX_CARRY_FOOD = 200
TANK_CREW_FOOD = 100
TANK_CREW_MAX_FOOD = 200
TANK_ATTACK_POWER = 3
VEHICLE_ROAD_BONUS = 0.5
TANK_VS_TANK_RICOCHET_CHANCE = 30
TANK_VS_INFANTRY_BONUS_DAMAGE = 2
TANK_ARMOR_ABSORPTION_DIVISOR = 10

# =============================================================================
# ARTILLERY COMBAT PARAMETERS
# =============================================================================
ARTILLERY_CREW_FOOD = 100
ARTILLERY_CREW_MAX_FOOD = 200
ARTILLERY_HIT_CHANCE_FIELD = 80
ARTILLERY_HIT_CHANCE_FOREST = 60
ARTILLERY_HIT_CHANCE_CITY = 40
ARTILLERY_ENTRENCH_PENALTY_DIVISOR = 2
ARTILLERY_MIN_HIT_CHANCE = 10
ARTILLERY_DAMAGE_MOD_FOREST = 0.7
ARTILLERY_DAMAGE_MOD_CITY = 0.8
ARTILLERY_ENTRENCH_DAMAGE_DIVISOR = 200

# =============================================================================
# RADAR EW PARAMETERS
# =============================================================================
RADAR_EW_INIT_MORALE = 100
RADAR_EW_CREW_FOOD = 100
RADAR_EW_CREW_MAX_FOOD = 200
RADAR_EW_STARVATION_TURNS = 2
RADAR_EW_STARVATION_MORALE_PENALTY = -10

# =============================================================================
# DRONE PARAMETERS
# =============================================================================
SOLDIER_UNIT_VISION_RANGE = 2
RECON_DRONE_MOVE_COST = 1
FPV_DRONE_MAX_AGE = 10
FPV_DRONE_VISION_RANGE = 2

# EW penalties
EW_PENALTY_RADAR_EW = 15
EW_PENALTY_TANK_JAMMER = 10
EW_PENALTY_MAX = 50

# FPV shootdown
FPV_SHOOTDOWN_MULTIPLIER_STACK = 0.5
FPV_KILL_DAMAGE_OTHER = 99

# FPV Operator
FPV_OPERATOR_MAX_CREW = 999
FPV_OPERATOR_INIT_MORALE = 100
FPV_OPERATOR_VISION_RANGE = 2
FPV_OPERATOR_RELOAD_AMMO = 5
FPV_OPERATOR_STARVATION_TURNS = 2
FPV_OPERATOR_STARVATION_MORALE_PENALTY = -10

# =============================================================================
# SUPPLY UNIT PARAMETERS
# =============================================================================
TRUCK_CREW_FOOD = 100
TRUCK_CREW_MAX_FOOD = 100
TRUCK_VISION_RANGE = 1
TRUCK_FPV_LOAD_LIMIT = 5

# Warehouse
WAREHOUSE_INIT_SUPPLIES = 1000
WAREHOUSE_MAX_SUPPLIES = 2000
WAREHOUSE_INIT_AMMO = 60
WAREHOUSE_MAX_AMMO = 150
WAREHOUSE_INIT_FUEL = 40
WAREHOUSE_MAX_FUEL = 100
WAREHOUSE_INIT_BATTERIES = 30
WAREHOUSE_MAX_BATTERIES = 80
WAREHOUSE_INIT_FPV_DRONES = 5
WAREHOUSE_INIT_RECON_DRONES = 3
WAREHOUSE_VISION_RANGE = 2
WAREHOUSE_REINFORCE_SUPPLIES = 500
WAREHOUSE_REINFORCE_AMMO = 30
WAREHOUSE_REINFORCE_FUEL = 20
WAREHOUSE_REINFORCE_BATTERIES = 15
WAREHOUSE_REINFORCE_RECON_DRONES = 1
WAREHOUSE_MAX_RECON_DRONES = 5
WAREHOUSE_REINFORCE_FPV_DRONES = 2
WAREHOUSE_MAX_FPV_DRONES = 10

# Recon Operator
RECON_OP_INIT_BATTERIES = 30
RECON_OP_MAX_BATTERIES = 30
RECON_OP_INIT_MORALE = 100
RECON_OP_DRONE_STORED = 1
RECON_OP_MAX_STORED = 1
RECON_OP_VISION_RANGE = 2
RECON_OP_STARVATION_TURNS = 2
RECON_OP_STARVATION_MORALE_PENALTY = -10

# Supply Cache
CACHE_MAX_SUPPLIES = 200
CACHE_MAX_AMMO = 100
CACHE_MAX_FUEL = 60
CACHE_MAX_BATTERIES = 30
CACHE_MAX_SLOTS = 30
CACHE_BUILD_TURNS = 5
CACHE_VISION_RANGE = 1

# =============================================================================
# COMBAT SYSTEM PARAMETERS
# =============================================================================
COMBAT_MAX_SHOTS_PER_ENGAGEMENT = 3
COMBAT_ENTRENCH_REDUCTION_DIVISOR = 30
COMBAT_DAMAGE_TO_HEALTH_MULTIPLIER = 20
COMBAT_COUNTER_ATTACK_DIVISOR = 2

# Tank vs Tank
COMBAT_TANK_RICOCHET_CHANCE = 30
COMBAT_TANK_ARMOR_ABSORB_DIVISOR = 15
COMBAT_TANK_CREW_DAMAGE_CHANCE = 40
COMBAT_TANK_CREW_DAMAGE_MIN = 10
COMBAT_TANK_CREW_DAMAGE_MAX = 30
COMBAT_TANK_DEFENDER_RICOCHET_CHANCE = 30
COMBAT_TANK_COUNTER_ARMOR_DIVISOR = 15

# Tank vs Infantry
COMBAT_TANK_VS_INF_BONUS_TARGETS = 2
COMBAT_SHRAPNEL_DAMAGE_MIN = 15
COMBAT_SHRAPNEL_DAMAGE_MAX = 40

# Infantry vs Tank
COMBAT_INF_VS_TANK_AMMO_COST = 3
COMBAT_GRENADE_HIT_CHANCE = 30
COMBAT_TANK_KILL_DAMAGE = 100

# General
COMBAT_DEFAULT_ATTACK_POWER = 3
COMBAT_FPV_KILL_DAMAGE = 99

# =============================================================================
# TURN MANAGER PARAMETERS
# =============================================================================
PHASE_TIMER_PLANNING = 30
PHASE_TIMER_DEFAULT = 20

# Artillery target priorities
ARTILLERY_TARGET_PRIORITY_WAREHOUSE = 10
ARTILLERY_TARGET_PRIORITY_CACHE = 8
ARTILLERY_TARGET_PRIORITY_TANK = 6
ARTILLERY_TARGET_PRIORITY_INFANTRY = 4
ARTILLERY_TARGET_PRIORITY_ARTILLERY = 5
ARTILLERY_TARGET_PRIORITY_OPERATOR = 3

# Starvation
STARVATION_DEATH_THRESHOLD_DIVISOR = 2
SOLDIER_UNIT_STARVATION_DAMAGE = 10
CACHE_ABANDON_CHANCE = 0.15

# Effect timers
EFFECT_TIMER_COMBAT = 30
EFFECT_TIMER_RICOCHET = 20
EFFECT_TIMER_EXPLOSION = 25
EFFECT_TIMER_KILL = 35
EFFECT_TIMER_PROJECTILE = 20

# Auto resupply
AUTO_RESUPPLY_RANGE = 15
AUTO_RESUPPLY_THRESHOLD = 0.25
CACHE_RESUPPLY_RANGE = 3
WAREHOUSE_RESUPPLY_RANGE = 1

# Resupply amounts per turn
RESUPPLY_FOOD_PER_SOLDIER = 2
RESUPPLY_AMMO_PER_SOLDIER = 2
RESUPPLY_TANK_FUEL = 5
RESUPPLY_TANK_AMMO = 3
RESUPPLY_TANK_CARRY_FOOD = 5
RESUPPLY_CREW_REINFORCE_COST = 2
RESUPPLY_CREW_REINFORCE_RATIO = 5
RESUPPLY_OPERATOR_BATTERIES = 5
RESUPPLY_OPERATOR_FOOD = 3
RESUPPLY_OPERATOR_AMMO = 3
RESUPPLY_ARTILLERY_AMMO = 3
RESUPPLY_ARTILLERY_SOLDIER_FOOD = 2
RESUPPLY_RADAR_EW_FUEL = 5
RESUPPLY_RADAR_EW_FOOD = 3
RESUPPLY_TRUCK_FUEL = 5

# Reinforcement spawn
TANK_SPAWN_OFFSET = 2
DRONE_SPAWN_BATTERY_COST = 5

# =============================================================================
# AI PARAMETERS
# =============================================================================
AI_ADVANTAGE_THRESHOLD = 0.55
AI_OFFENSIVE_MIN_TURN = 15
AI_RECON_DEPLOY_INTERVAL = 8

# Strategic points
AI_STRATEGIC_POINT_MIN_DIST_WH = 8
AI_STRATEGIC_POINT_MAX_DIST_WH = 25
AI_STRATEGIC_POINT_MIN_DIST_PLAYER = 6
AI_STRATEGIC_POINT_SPACING = 4

# Warehouse management
AI_CLEAR_WAREHOUSE_RADIUS = 4
AI_CLEAR_WAREHOUSE_MIN_DIST = 3

# Group formation
AI_MIN_INFANTRY_TO_FORM_GROUP = 2
AI_MAX_INFANTRY_PER_GROUP = 3
AI_DEPLOY_PROXIMITY = 8

# Fortification
AI_FORTIFY_MAX_WH_DISTANCE = 8
AI_FORTIFY_ENTRENCH_THRESHOLD = 0.5
AI_FORTIFY_MIN_FRACTION_DIVISOR = 2

# Truck management
AI_TRUCK_LOAD_LIMIT = 100
AI_HUNGRY_THRESHOLD_FRACTION = 0.7
AI_TRUCK_LOAD_PER_RESOURCE = 10

# Offensive
AI_OFFENSIVE_GROUP_FRACTION = 2

# Drone management
AI_MAX_DRONES = 3
AI_DRONE_SCOUT_START_TURN = 10
AI_DRONE_PATROL_OFFSET = 5
AI_DRONE_MANAGEMENT_START_TURN = 10
AI_DRONE_PATROL_OFFSET_INITIAL = 5
AI_DRONE_PATROL_OFFSET_RETARGET = 8

# =============================================================================
# ACTION MANAGER PARAMETERS
# =============================================================================
CACHE_MIN_DISTANCE = 3
GARRISON_EXIT_SOLDIERS = 6
TANK_CELL_ATTACK_RANGE = 2
TANK_VS_INF_MELEE_BONUS = 2
WAREHOUSE_MOVE_MAX_DISTANCE = 3

# =============================================================================
# SUPPLY LOGISTICS PARAMETERS
# =============================================================================
PATHFIND_MAX_COST = 99
TRUCK_MANUAL_LOAD_LIMIT = 10
TRUCK_AUTO_LOAD_LIMIT = 10
TRUCK_TRANSFER_TO_LIMIT = 20
TRUCK_TRANSFER_FROM_LIMIT = 20
WAYPOINT_MARCH_MORALE_PENALTY = 3

# =============================================================================
# RESOURCE TRANSFER LIMITS
# =============================================================================
TRANSFER_WAREHOUSE_TO_TANK_LIMIT = 10
TRANSFER_WAREHOUSE_TO_ARTILLERY_LIMIT = 10
TRANSFER_WAREHOUSE_TO_RECON_BATTERY_LIMIT = 10
TRANSFER_WAREHOUSE_TO_FPV_DRONE_LIMIT = 5
TRANSFER_WAREHOUSE_TO_FPV_AMMO_LIMIT = 10

TRANSFER_TRUCK_TO_TANK_AMMO_LIMIT = 10
TRANSFER_TRUCK_TO_TANK_FUEL_LIMIT = 10
TRANSFER_TRUCK_TO_TANK_FOOD_LIMIT = 10
TRANSFER_TRUCK_TO_RECON_BATTERY_LIMIT = 10
TRANSFER_TRUCK_TO_RECON_FOOD_AMMO_LIMIT = 5
TRANSFER_TRUCK_TO_FPV_FOOD_AMMO_LIMIT = 5
TRANSFER_TRUCK_TO_SOLDIER_FOOD_AMMO_LIMIT = 5
TRANSFER_TRUCK_TO_TRUCK_FUEL_LIMIT = 20
TRANSFER_TRUCK_TO_ARTILLERY_LIMIT = 5

TRANSFER_SOLDIER_TO_INFANTRY_LIMIT = 3
TRANSFER_SOLDIER_TO_SOLDIER_LIMIT = 3

TRANSFER_TANK_SURPLUS_FOOD_THRESHOLD = 100
TRANSFER_TANK_SURPLUS_FOOD_LIMIT = 3
TRANSFER_TANK_TO_SOLDIER_AMMO_LIMIT = 3

TRANSFER_ARTILLERY_SURPLUS_FOOD_THRESHOLD = 100

TRANSFER_DEFAULT_LIMIT = 5
