SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

TILE_SIZE = 48
PANEL_WIDTH = 300
ZOOM_MIN = 0.3
ZOOM_MAX = 2.0
ZOOM_STEP = 0.1
CAMERA_SCROLL_SPEED = 12
EDGE_SCROLL_SPEED = 8

MAP_OFFSET_X = 0
MAP_OFFSET_Y = 0

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GRAY = (100, 100, 100)
LIGHT_GRAY = (180, 180, 180)
DARK_GRAY = (60, 60, 60)
RED = (220, 50, 50)
GREEN = (50, 200, 50)
BLUE = (50, 100, 220)
YELLOW = (220, 220, 50)
ORANGE = (220, 140, 20)
BROWN = (140, 90, 30)
DARK_GREEN = (30, 80, 30)
CYAN = (50, 200, 200)
PURPLE = (160, 50, 200)
BEIGE = (210, 190, 140)
DARK_BLUE = (20, 40, 100)

# Terrain types
FIELD = 0
FOREST = 1
CITY = 2
ROAD = 3
RIVER = 4

TERRAIN_COLORS = {
    FIELD: (100, 160, 60),
    FOREST: (30, 90, 30),
    CITY: (160, 140, 120),
    ROAD: (140, 130, 110),
    RIVER: (50, 100, 200),
}

TERRAIN_NAMES = {
    FIELD: "Поле",
    FOREST: "Лес",
    CITY: "Город",
    ROAD: "Дорога",
    RIVER: "Река",
}

TERRAIN_MOVEMENT_COST = {
    FIELD: 1,
    FOREST: 2,
    CITY: 1,
    ROAD: 0.5,
    RIVER: 99,
}

TERRAIN_DEFENSE_BONUS = {
    FIELD: 0,
    FOREST: 20,
    CITY: 40,
    ROAD: 0,
    RIVER: 0,
}

TERRAIN_COVER_BONUS = {
    FIELD: 0,
    FOREST: 25,
    CITY: 50,
    ROAD: 0,
    RIVER: 0,
}

# HoMM-style movement points per turn
# Пехота = 1 шаг за ход (любая местность)
# Техника = больше очков, зависит от местности
INFANTRY_MOVE_POINTS = 10   # Хватит на любую клетку, но лимит 1 шаг
TANK_MOVE_POINTS = 4
TRUCK_MOVE_POINTS = 4
ARTILLERY_MOVE_POINTS = 3
DRONE_MOVE_POINTS = 6
SOLDIER_UNIT_MOVE_POINTS = 10  # 1 шаг за ход
RADAR_EW_MOVE_POINTS = 3

# Максимальное количество шагов за ход
INFANTRY_STEPS_PER_TURN = 1
TANK_STEPS_PER_TURN = 3
TRUCK_STEPS_PER_TURN = 3
ARTILLERY_STEPS_PER_TURN = 2
DRONE_STEPS_PER_TURN = 5
SOLDIER_STEPS_PER_TURN = 1
RADAR_EW_STEPS_PER_TURN = 2

# Vision
VISION_RANGE = {
    "infantry": 2,
    "tank": 3,
    "drone": 5,
    "artillery": 2,
    "soldier_unit": 2,
    "radar_ew": 3,
}

# Unit types
INFANTRY = "infantry"
TANK = "tank"
RECON_DRONE = "recon_drone"
FPV_DRONE = "fpv_drone"
FPV_OPERATOR = "fpv_operator"
SUPPLY_TRUCK = "supply_truck"
WAREHOUSE = "warehouse"
RECON_OPERATOR = "recon_operator"
ARTILLERY = "artillery"
SOLDIER_UNIT = "soldier_unit"
RADAR_EW = "radar_ew"

# Unit parameters
INFANTRY_INIT_SOLDIERS = 8
INFANTRY_MAX_SOLDIERS = 999
INFANTRY_BASE_FOOD_PER_TURN = 1
INFANTRY_MAX_AMMO = 30
INFANTRY_MAX_FOOD = 100
INFANTRY_MAX_ENTRENCH = 100
INFANTRY_ATTACK_RANGE = 1
INFANTRY_BASE_HIT_CHANCE = 60
INFANTRY_MORALE_MAX = 100
SOLDIER_FOOD_WEIGHT = 0.3
SOLDIER_WEIGHT = 10
SOLDIER_MAX_FOOD = 40
SOLDIER_MAX_AMMO = 5
SOLDIER_FOOD_PER_TURN = 1
SOLDIER_FOOD_INTERVAL = 1
SOLDIER_TURNS_WITHOUT_FOOD_DEATH = 3
SOLDIER_CARRY_CAPACITY = 40

TANK_INIT_CREW = 3
TANK_MIN_CREW = 3
TANK_MAX_CREW = 999
TANK_MAX_ARMOR = 100
TANK_MAX_AMMO = 15
TANK_MAX_FUEL = 30
TANK_ATTACK_RANGE = 2
TANK_BASE_HIT_CHANCE = 90
TANK_CARRY_CAPACITY = 20
TANK_CARRY_FOOD = 0
TANK_CARRY_AMMO = 0

ARTILLERY_INIT_CREW = 4
ARTILLERY_MAX_CREW = 999
ARTILLERY_MAX_AMMO = 8
ARTILLERY_MAX_ENTRENCH = 100
ARTILLERY_ATTACK_RANGE = 5
ARTILLERY_BARRAGE_RANGE = 30
ARTILLERY_DAMAGE = 4

RADAR_EW = "radar_ew"
RADAR_EW_INIT_CREW = 4
RADAR_EW_MIN_CREW = 2
RADAR_EW_MAX_CREW = 999
RADAR_EW_MAX_FOOD = 100
RADAR_EW_MAX_AMMO = 20
RADAR_EW_JAM_RANGE = 5
RADAR_EW_MAX_FUEL = 60
RADAR_EW_FUEL_PER_TURN = 3

MAP_WIDTH = 75
MAP_HEIGHT = 54

DRONE_MAX_BATTERY = 96
DRONE_VISION_RANGE = 6
DRONE_LOW_BATTERY_THRESHOLD = 20

FPV_OPERATOR_INIT_CREW = 2
FPV_OPERATOR_MIN_CREW = 2
FPV_OPERATOR_MAX_STOCK = 5
FPV_OPERATOR_MAX_FOOD = 100
FPV_OPERATOR_MAX_AMMO = 30
FPV_OPERATOR_RANGE = 30
FPV_AUTO_TARGET = True
FPV_MOVE_SPEED = 5
FPV_MAX_PER_TURN = 1

FPV_HIT_CHANCE_BASE = 0.80
FPV_HIT_EW_PENALTY = 0.20
FPV_HIT_FOREST_PENALTY = 0.20
FPV_HIT_CITY_PENALTY = 0.10
FPV_INFANTRY_SHOOTDOWN_CHANCE = 0.15
FPV_NO_LOS_PENALTY = 0.25

TRUCK_CARGO_CAPACITY = 20
TRUCK_MAX_WEIGHT = 300
TRUCK_MAX_FUEL = 15
TRUCK_INIT_CREW = 1
TRUCK_MIN_CREW = 1
TRUCK_MAX_CREW = 999
RECON_OPERATOR_INIT_CREW = 1
RECON_OPERATOR_MIN_CREW = 1
RECON_OPERATOR_MAX_CREW = 999
RECON_OPERATOR_MAX_FOOD = 100
RECON_OPERATOR_MAX_AMMO = 20

WAREHOUSE_CAPACITY = 100

# Radar
RADAR_RANGE = 25
RADAR_WAVE_SPEED = 0.5
RADAR_OPERATOR_RANGE = 25

# Supply consumption
FOOD_CONSUMPTION_INTERVAL = 1
FUEL_CONSUMPTION = 1

# Combat
FPV_HIT_CHANCE_BASE = 0.8
FPV_DAMAGE_INFANTRY = 5
FPV_DAMAGE_ARMOR = 30

# Turns
MAX_TURNS = 40
SUPPLY_REINFORCEMENT_INTERVAL = 25

# Unit reinforcement intervals (in turns)
REINFORCEMENT_INFANTRY_INTERVAL = 25
REINFORCEMENT_TANK_INTERVAL = 25
REINFORCEMENT_DRONE_INTERVAL = 25
REINFORCEMENT_FPV_INTERVAL = 25

# Cargo types
CARGO_SUPPLIES = "supplies"
CARGO_AMMO = "ammo"
CARGO_FUEL = "fuel"
CARGO_BATTERIES = "batteries"
CARGO_FPV_DRONE = "fpv_drone"
CARGO_RECON_DRONE = "recon_drone"
CARGO_NAMES = {
    CARGO_SUPPLIES: "Припасы",
    CARGO_AMMO: "Боезапас",
    CARGO_FUEL: "Топливо",
    CARGO_BATTERIES: "Батареи",
    CARGO_FPV_DRONE: "FPV-дроны",
    CARGO_RECON_DRONE: "Разведдроны",
}

CARGO_WEIGHT_PER_UNIT = {
    CARGO_SUPPLIES: 5,
    CARGO_AMMO: 10,
    CARGO_FUEL: 8,
    CARGO_BATTERIES: 3,
    CARGO_FPV_DRONE: 15,
    CARGO_RECON_DRONE: 20,
}

# Factions
PLAYER = 0
ENEMY = 1

# Game phases
PHASE_PLANNING = 0
PHASE_MOVEMENT = 1
PHASE_DETECTION = 2
PHASE_RANGED_COMBAT = 3
PHASE_CLOSE_COMBAT = 4
PHASE_LOGISTICS = 5
PHASE_ENTRENCH = 6
PHASE_ENEMY_TURN = 7

PHASE_NAMES = {
    PHASE_PLANNING: "Планирование",
    PHASE_MOVEMENT: "Движение",
    PHASE_DETECTION: "Обнаружение",
    PHASE_RANGED_COMBAT: "Дальний бой",
    PHASE_CLOSE_COMBAT: "Ближний бой",
    PHASE_LOGISTICS: "Логистика",
    PHASE_ENTRENCH: "Укрепления",
    PHASE_ENEMY_TURN: "Ход противника",
}

# Directions
DIRECTIONS = [(0, -1), (0, 1), (-1, 0), (1, 0)]
